[package]
edition = "2021"
name = "wasm-web-push"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ece = "2.2.0"
getrandom = {version = "0.2.10", features = ["js"]}
wasm-bindgen = "0.2"
# web-push = "0.9.5"
